specification:
  product: ga_s2b_ard_nbar_granule
  measurements: 
    - 'nbar_blue'
    - 'nbar_green'
    - 'nbar_red'
    - 'nbar_nir_1'
    - 'nbar_swir_2'
    - 'nbar_swir_3'
    - 'fmask'
  measurement_renames:
    nbar_blue: nbart_blue
    nbar_green: nbart_green
    nbar_red: nbart_red
    nbar_nir_1: nbart_nir
    nbar_swir_2: nbart_swir_1
    nbar_swir_3: nbart_swir_2
    fmask: fmask

  transform: wofs.virtualproduct.WOfSClassifier
  override_product_family: ard
  basis: 'nbar_nir_1'

  transform_args:
    c2: False
    dsm_path:  's3://deafrica-data/ancillary/dem/srtm_africa.tif'

output:
  location: /tmp/alchemist
  nodata: 1
  dtype: uint8

  write_data_settings:
    overview_resampling: mode

  metadata:
    product_family: wofs
    producer: ga.gov.au
    dataset_version: 0.0.1
  properties:
    dea:dataset_maturity: interim

processing:
  dask_chunks:
    x: 3000
    y: 3000
