specification:
  product: ga_s2b_ard_nbar_granule
  measurements: 
    - blue
    - green
    - red
    - nir_1
    - swir_1
    - swir_2
    - SCL
  measurement_renames:
    blue: nbart_blue
    green: nbart_green
    red: nbart_red
    nir_1: nbart_nir
    swir_1: nbart_swir_1
    swir_2: nbart_swir_2
    SCL: fmask

  transform: wofs.virtualproduct.WOfSClassifier
  override_product_family: ard
  basis: SCL

  transform_args:
    c2: False
    dsm_path:  's3://deafrica-data/ancillary/dem/srtm_africa.tif'

output:
  location: /tmp/alchemist
  nodata: 1
  dtype: uint8

  write_data_settings:
    overview_resampling: mode

  metadata:
    product_family: wofs
    producer: ga.gov.au
    dataset_version: 0.0.1
  properties:
    dea:dataset_maturity: interim

processing:
  dask_chunks:
    x: 600
    y: 600
