name: Lint, Test Code and Push Image

on:
  pull_request:
    paths:
      - '**'

  push:
    paths:
      - '**'

  release:
    types:
      - created

env:
  IMAGE_NAME: opendatacube/datacube-alchemist

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Build image with cache
      uses: whoan/docker-build-with-cache-action@v4
      with:
        image_name: ${{ env.IMAGE_NAME }}
        username: "${{ secrets.DOCKER_USER }}"
        password: "${{ secrets.DOCKER_PASS }}"
        image_tag: test
        push_image_and_stages: false
        build_extra_args: "--build-arg=ENVIRONMENT=test"

    - name: Run linting
      run: |
        make lint

    - name: Run tests
      run: |
        make test

    - name: Get the git tag
      run: |
        git fetch --tags
        echo ::set-env name=GITTAG::$(git describe --tag)
        echo $GITTAG

    - name: Build and Push unstable Docker Image from PR
      uses: whoan/docker-build-with-cache-action@v4
      if: github.ref == 'refs/heads/master'
      with:
        image_name: ${{ env.IMAGE_NAME }}
        username: "${{ secrets.DOCKER_USER }}"
        password: "${{ secrets.DOCKER_PASS }}"
        image_tag: latest,${{ env.GITTAG }}
        build_extra_args: "--build-arg=ENVIRONMENT=deployment"
